# Generated by Django 5.0.1 on 2024-01-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('tel_number', models.CharField(max_length=13)),
                ('actions', models.BooleanField(default=False)),
                ('sponsorship_sum', models.CharField(max_length=20)),
                ('spent_sum', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ALL', 'Barchasi'), ('NEW', 'Yangi'), ('MOD', 'Modernizatsiyada'), ('APP', 'Tasdiqlangan'), ('CAN', 'Bekor qilingan')], default='ALL', max_length=3)),
                ('person_type', models.CharField(choices=[('IND', 'Jismoniy'), ('LEG', 'Yuridik')], default='IND', max_length=3)),
                ('payment_type', models.CharField(choices=[('EXP1', 'Example1'), ('EXP2', 'Example2')], default='EXP1', max_length=4)),
                ('organization', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'ordering': ['last_name'],
                'indexes': [models.Index(fields=['last_name'], name='api_sponsor_last_na_1a730d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('tel_number', models.CharField(max_length=13)),
                ('actions', models.BooleanField(default=False)),
                ('student_type', models.CharField(choices=[('GR', 'Bakalavr'), ('MG', 'Magistr')], max_length=2)),
                ('allocated_sum', models.CharField(default='0', max_length=20)),
                ('contract_amount', models.CharField(max_length=20)),
                ('hti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='htis', to='api.hti')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorAllocated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_sum', models.CharField(default='0', max_length=20)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='api.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name'], name='api_student_last_na_9de1e0_idx'),
        ),
    ]
